### PR TITLE
#7 Get pain log test pass

### PR DESCRIPTION
**Pull request by hiendinhngoc**

### CODE REVIEW

**Comment by lortza** [comment]
Hi @hiendinhngoc. Thank you for your work, but there is already a PR open on this issue. I will be closing your PR.

**Comment by hiendinhngoc** [comment]
> Hi @hiendinhngoc. Thank you for your work, but there is already a PR open on this issue. I will be closing your PR.

Sorry @lortza you meant PR #78? if yes, it's only about exercise logs.

**Comment by lortza** [comment]
Ah, I see what is happening here. We are using github differently. You are seeing a pull request with incomplete work and completing that work. I am seeing the pull request with incomplete work as a work-in-progress. It is my understanding that @kelseyhuse30 will be pushing the rest of those tests soon.

**Comment by hiendinhngoc** [comment]
Oh, got it @lortza

**Pull request closed without merging**
